name: Build and Test

on:
  pull_request:
    branches: [ master ]

env:
  dotnet-version: 6.0.x # SDK Version for building Dafny

jobs:
  singletons:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{env.dotnet-version}}
    - name: Checkout Dafny
      uses: actions/checkout@v3
      with:
        path: dafny
    - name: Restore tools
      working-directory: dafny
      run: dotnet tool restore
    - name: Get Boogie Version
      run: |
        sudo apt-get install -qq libxml2-utils
        echo "boogieVersion=`xmllint --xpath "//PackageReference[@Include='Boogie.ExecutionEngine']/@Version" dafny/Source/DafnyCore/DafnyCore.csproj | grep -Po 'Version="\K.*?(?=")'`" >> $GITHUB_ENV
    - name: Attempt custom Boogie patch
      working-directory: dafny
      run: git apply customBoogie.patch
    - name: Checkout Boogie
      uses: actions/checkout@v3
      with:
        repository: boogie-org/boogie
        path: dafny/boogie
        ref: v${{ env.boogieVersion }}
    - name: Build Dafny with local Boogie
      working-directory: dafny
      run: dotnet build Source/Dafny.sln
    - name: Check whitespace and style
      working-directory: dafny
      run: dotnet tool run dotnet-format -w -s error --check Source/Dafny.sln --exclude DafnyCore/Scanner.cs --exclude DafnyCore/Parser.cs
    - name: Create NuGet package (just to make sure it works)
      run: dotnet pack --no-build dafny/Source/Dafny.sln

  check-deep-tests:
    uses: ./.github/workflows/check-deep-tests-reusable.yml
    with:
      branch: master

  integration-tests:
    needs: check-deep-tests
    if: always() && (needs.check-deep-tests.result == 'success' || contains(github.event.pull_request.labels.*.name, 'run-deep-tests'))
    uses: ./.github/workflows/integration-tests-reusable.yml
    with:
      # By default run only on one platform, but run on all platforms if the PR has the "run-deep-tests"
      # label, and skip checking the nightly build above.
      # This is the best way to fix an issue in master that was only caught by the nightly build.
      all_platforms: ${{ contains(github.event.pull_request.labels.*.name, 'run-deep-tests') }}
      num_shards: 5
