name: Build and Test

on:
  push:
    branches: [ master, split-off-deep-tests-in-CI ]
  pull_request:
    branches: [ master ]

env:
  dotnet-version: 6.0.x # SDK Version for building Dafny
  
jobs:
  singletons:
    runs-on: ubuntu-18.04
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: ${{env.dotnet-version}}
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        path: dafny
    - name: Restore tools
      working-directory: dafny
      run: dotnet tool restore
    - name: Get XML
      id: boogieVersion
      uses: QwerMike/xpath-action@v1
      with:
        filename: 'dafny/Source/Dafny/DafnyPipeline.csproj'
        expression: "//PackageReference[@Include='Boogie.ExecutionEngine']/@Version"

    - uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ steps.boogieVersion.outputs.result }}
        regex: ' Version="([\d\.]+)"'
    - name: Attempt custom Boogie patch
      working-directory: dafny
      run: git apply customBoogie.patch
    - name: Checkout Boogie
      uses: actions/checkout@v2
      with:
        repository: boogie-org/boogie
        path: dafny/boogie
        ref: v${{ steps.regex-match.outputs.group1 }}
    - name: Build Dafny with local Boogie
      working-directory: dafny
      run: dotnet build Source/Dafny.sln
    - name: Check whitespace and style
      working-directory: dafny
      run: dotnet tool run dotnet-format -w -s error --check Source/Dafny.sln --exclude Dafny/Scanner.cs --exclude Dafny/Parser.cs
      
  integration-tests:
    uses: ./.github/workflowsintegration-tests.yml
    with:
      all_platforms: false
