name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  dotnet-version: 6.0.x # SDK Version for building Dafny
  
jobs:
  check-deep-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // This API doesn't support filtering by SHA, so we just
            // fetch the first page and scan manually.
            // That means if the run is fairly old it may be missed,
            // but that should be rare.
            const runs = github.rest.actions.listWorkflowRuns({
              owner: 'dafny-lang',
              repo: 'dafny',
              workflow_id: 'deep-tests.yml'
            })
            // These are ordered by creation time, so decide based on the first
            // run for this SHA we see.
            for (const run of runs) {
              if (run.sha == context.sha) {
                if (run.conclusion != "success") {
                  core.setFailed(`Last run of deep tests on $context.sha did not succeed!`)
                } else {
                  // The SHA is fully-tested, exit with success
                  return
                }
              }
            }
            core.setFailed(`No run of deep tests found for $context.sha!`)

  publish-release:
    # needs: check-deep-tests
    runs-on: macos-latest
    steps:
    - id: get-version
      uses: battila7/get-version-action@v2
    - uses: actions/setup-python@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: ${{env.dotnet-version}}
    - name: C++ for ubuntu 18.04
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo apt-get install -y build-essential
    - name: Choose the right C++ for ubuntu 18.04
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60
    - uses: actions/setup-python@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v1
    - run: npm install bignumber.js
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        path: dafny
        submodules: true
    - name: Install latex pandoc
      run: |
        brew install pandoc
        brew install --cask basictex
        eval "$(/usr/libexec/path_helper)"
        sudo tlmgr update --self
        sudo tlmgr install framed tcolorbox environ trimspaces unicode-math
        pandoc -v
        which latex || echo NOT FOUND latex
        which xelatex || echo NOT FOUND xelatex
        sudo gem install rouge
    - name: Package release files
      run: |
        eval "$(/usr/libexec/path_helper)"
        python dafny/Scripts/package.py ${{ steps.get_version.outputs.version-without-v }} --github_secret=${{ secrets.GITHUB_TOKEN }}
    - name: Create draft GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: Dafny ${{ steps.get_version.outputs.version-without-v }}
        draft: true
        files: |
          Package/dafny-${{ steps.get_version.outputs.version-without-v }}*
          Package/DafnyRef.pdf
        fail_on_unmatched_files: true
