name: Run XUnit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

## In the matrix:
##  os - name of the Github actions runner
##  suffix - name used in the description of the job
##  z3 - name of the Z3 asset at the 'z3BaseUri' URL
##  chmod - whether the Z3 download needs execute permissions added
##  coverage -- unused?

jobs:
  build:
    runs-on: ${{matrix.os}}
    name: ${{matrix.suffix}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            suffix: ubuntu-20.04
            z3: z3-4.8.5-x64-ubuntu-16.04
            chmod: true
            coverage: true
          - os: windows-2019
            suffix: win
            z3: z3-4.8.5-x64-win
            chmod: false
            coverage: false
          - os: macos-latest
            suffix: osx
            z3: z3-4.8.5-x64-osx-10.14.2
            chmod: true
            coverage: false
    env:
      solutionPath: Source/Dafny.sln
      z3BaseUri: https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5
      Logging__LogLevel__Microsoft: Debug
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ${{env.solutionPath}}
    - name: Load Z3
      shell: pwsh
      run: |
        Invoke-WebRequest ${{env.z3BaseUri}}/${{matrix.z3}}.zip -OutFile z3.zip
        Expand-Archive z3.zip .
        Remove-Item z3.zip
        Copy-Item ${{matrix.z3}} Binaries/z3 -Recurse
    - name: Set Z3 Permissions
      if: ${{matrix.chmod}}
      run: |
        chmod +x Binaries/z3/bin/z3
    - name: Build
      run: dotnet build -warnaserror --no-restore ${{env.solutionPath}}
    - name: Run DafnyLanguageServer Tests
      run: |
        dotnet test --no-restore --verbosity normal --logger trx Source/DafnyLanguageServer.Test
        dotnet test --no-restore --verbosity normal --logger trx Source/DafnyLanguageServer.Test
    - name: Run DafnyDriver Tests
      run: dotnet test --no-restore --verbosity normal --logger trx Source/DafnyDriver.Test
    - name: Run DafnyPipeline Tests
      run: dotnet test --no-restore --verbosity normal --logger trx Source/DafnyPipeline.Test
    - name: Run DafnyTestGeneration Tests
      run: dotnet test --no-restore --verbosity normal --logger trx Source/DafnyTestGeneration.Test
    - name: Run AutoExtern Tests
      run: dotnet test --no-restore --verbosity normal --logger trx Source/AutoExtern.Test
    - name: Run DafnyRuntime Tests
      run: dotnet test --no-restore --verbosity normal --logger trx Source/DafnyRuntime.Tests
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: unit-test-results-${{ matrix.os }}
        path: Source/*/TestResults/*.trx
